# Listing 2.1 Pandas DataFrame    

In [1]:
import pandas as pd
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
print(df)

   A  B
0  1  4
1  2  5
2  3  6


# Listing 2.2 Numpy

In [2]:
import numpy as np
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


# Lisiting 2.3 Pandas Series

In [3]:
import pandas as pd
s = pd.Series([1, 2, 3])
print(s)

0    1
1    2
2    3
dtype: int64


# Listing 2.4 Convert to integer

In [4]:
x = int(3.14)  
print(x)

3


# Listing 2.5 Convert to float

In [5]:
x = float(3) 
print(x)

3.0


# Listing 2.6 Convert to string

In [6]:
x = str(3.14) 
x

'3.14'

# Listing 2.7 Convert to list

In [7]:
x = list((1, 2, 3))  
print(x)

[1, 2, 3]


# Listing 2.8 Convert to tuple

In [8]:
x = tuple([1, 2, 3])  
print(x)

(1, 2, 3)


# Listing 2.9 Convert to set

In [9]:
x = set([1, 2, 2, 3])  
print(x)

{1, 2, 3}


# Listing 2.10 Convert to dict

In [10]:
x = dict([('a', 1), ('b', 2)])  
print(x)

{'a': 1, 'b': 2}


# Listing 2.11 Convert to numpy array

In [11]:
import pandas as pd
import numpy as np

data = {
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8],
    'C': [9, 10, 11, 12]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

numpy_array = df.to_numpy()
print("\nConverted to numpy array:\n", numpy_array)

Original DataFrame:
    A  B   C
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12

Converted to numpy array:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


# Listing 2.12 Convert to Pandas Dataframe

In [12]:
import numpy as np
import pandas as pd

numpy_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original numpy array:\n", numpy_array)

df = pd.DataFrame(numpy_array, columns=['Column1', 'Column2', 'Column3'])
print("\nConverted to DataFrame:\n", df)

Original numpy array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Converted to DataFrame:
    Column1  Column2  Column3
0        1        2        3
1        4        5        6
2        7        8        9


# Listing 2.13 Pandas Series

In [13]:
import pandas as pd
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
series=df['A']
print(series)

0    1
1    2
2    3
Name: A, dtype: int64


# Listing 2.14 Pandas DataFrame

In [14]:
data = {
        'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'City': ['New York', 'Los Angeles', 'Chicago']
    }
df = pd.DataFrame(data)
print(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


# Listing 2.15 Numpy Array

In [15]:
import numpy as np
array = np.array([1, 2, 3, 4, 5])
print(array)

[1 2 3 4 5]


# Listing 2.16 Numpy Matrix

In [16]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Listing 2.17 Creating Numpy Arrays

In [17]:
zeros = np.zeros((3, 3))  
ones = np.ones((2, 2))  
print(zeros)
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


# Listing 2.18 Array Operations

In [23]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
sum_array = array1 + array2  
print("array1=",array1)
print("array2=",array2)
print("sum_array=",sum_array)

array1= [1 2 3]
array2= [4 5 6]
sum_array= [5 7 9]


# Listing 2.19 Mathematical Functions

In [27]:
array = np.array([1, 2, 3, 4, 5])
print("array=",array)
print("square root=",np.sqrt(array))  
print("mean=",np.mean(array))  

array= [1 2 3 4 5]
square root= [1.         1.41421356 1.73205081 2.         2.23606798]
mean= 3.0


# Listing 2.20 Indexing and Slicing

In [30]:
array = np.array([1, 2, 3, 4, 5])
print("array=",array)
print("second element=array[1]=",array[1])  
print("From second to fourth elements=",  array[1:4]) 
array[2] = 10  
print("new array after changing third element value=",array)

array= [1 2 3 4 5]
second element=array[1]= 2
From second to fourth elements= [2 3 4]
new array after changing third element value= [ 1  2 10  4  5]


# Listing 2.21 Reshaping Arrays

In [21]:
array = np.array([[1, 2, 3], [4, 5, 6]])
reshaped = array.reshape((3, 2))  
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]
